# Generated by Django 4.2.16 on 2025-01-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
