# Generated by Django 4.2.16 on 2025-01-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
